import Head from 'next/head'
import Image from 'next/image'
import Moment from 'react-moment'
import styles from '../styles/Home.module.css'
import { GetStaticProps } from 'next'

export default function Home({schedule}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Splatoon3 Stage Schedule
        </h1>

        <div className={styles.entry}>
            <h2>Current Stages</h2>
            <h3 className='stage-schedule'>
              <Moment format="YY/MM/DD H:mm">
                  {schedule.result.regular[0].start_time}
              </Moment>
              {' '}〜{' '}
              <Moment format="YY/MM/DD H:mm">
                  {schedule.result.regular[0].end_time}
              </Moment>
            </h3>
            <div className={styles.rules}>
              <div>
                <h3>
                ナワバリバトル
                </h3>
                <ul className={styles.stageList}>
                    <li>
                      <p>{schedule.result.regular[0].stages[0].name}</p>
                      <Image
                        src={schedule.result.regular[0].stages[0].image}
                        width={128}
                        height={64}
                        alt="stage-pic"
                      />
                    </li>
                    <li>
                      <p>{schedule.result.regular[0].stages[1].name}</p>
                      <Image
                          src={schedule.result.regular[0].stages[1].image}
                          width={128}
                          height={64}
                          alt="stage-pic"
                        />
                    </li>
                </ul>
              </div>
              <div>
                <h3>
                バンカラマッチ(チャレンジ)<br />({schedule.result.bankara_challenge[0].rule.name})
                </h3>
                <ul className={styles.stageList}>
                    <li>
                      <p>{schedule.result.bankara_challenge[0].stages[0].name}</p>
                      <Image
                          src={schedule.result.bankara_challenge[0].stages[0].image}
                          width={128}
                          height={64}
                          alt="stage-pic"
                        />
                    </li>
                    <li>
                      <p>{schedule.result.bankara_challenge[0].stages[1].name}</p>
                      <Image
                          src={schedule.result.bankara_challenge[0].stages[1].image}
                          width={128}
                          height={64}
                          alt="stage-pic"
                        />
                    </li>
                </ul>
              </div>
              <div>
                <h3>
                バンカラマッチ(オープン)<br />({schedule.result.bankara_open[0].rule.name})
                </h3>
                <ul className={styles.stageList}>
                    <li>
                      <p>{schedule.result.bankara_open[0].stages[0].name}</p>
                      <Image
                          src={schedule.result.bankara_open[0].stages[0].image}
                          width={128}
                          height={64}
                          alt="stage-pic"
                        />
                    </li>
                    <li>
                      <p>{schedule.result.bankara_open[0].stages[1].name}</p>
                      <Image
                          src={schedule.result.bankara_open[0].stages[1].image}
                          width={128}
                          height={64}
                          alt="stage-pic"
                        />
                    </li>
                </ul>
              </div>
            </div>
        </div>



      </main>

      <footer className={styles.footer}>
        aaa
      </footer>
    </div>
  )
}

export const getStaticProps = async() => {
// export async function getStaticProps() でも同じ
  const res = await fetch(`https://spla3.yuu26.com/api/schedule`)
  const schedule = await res.json()
  //console.log("-----------------------------------------------------------------------------")
  //console.log(schedule.result.regular[0])

  return {
    props: { schedule }, // will be passed to the page component as props
  }
}