import Head from 'next/head'
import Image from 'next/image'
import Moment from 'react-moment'
import styles from '../styles/Home.module.css'
import DefaultStages from '../component/DefaultStages.js'
import { GetStaticProps } from 'next'

export default function Home({schedule}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Splatoon3 Stage Schedule
        </h1>
        <DefaultStages schedule={schedule}></DefaultStages>
        

      </main>

      <footer className={styles.footer}>
        aaa
      </footer>
    </div>
  )
}

export const getStaticProps = async() => {
// export async function getStaticProps() でも同じ
  const res = await fetch(`https://spla3.yuu26.com/api/schedule`)
  const schedule = await res.json()
  //console.log("-----------------------------------------------------------------------------")
  //console.log(schedule.result.regular[0])

  return {
    props: { schedule }, // will be passed to the page component as props
  }
}