import Head from 'next/head'
import Image from 'next/image'
import Moment from 'react-moment'
import styles from '../styles/Home.module.css'
import { GetStaticProps } from 'next'

export default function Home({schedule}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          XXX
        </h1>

        <div>
            <h2>
            {schedule.result.regular[0].rule.name}
            </h2>
        
        <Moment format="YYYY/MM/DD H:mm">
            {schedule.result.regular[0].start_time}
        </Moment>
        〜
        <Moment format="YYYY/MM/DD H:mm">
            {schedule.result.regular[0].end_time}
        </Moment>
        <ul>
            <li>
                {schedule.result.regular[0].stages[0].name}
            </li>
            <li>
                {schedule.result.regular[0].stages[1].name}
            </li>
        </ul>
       
        </div>



      </main>

      <footer className={styles.footer}>
        aaa
      </footer>
    </div>
  )
}

export const getStaticProps = async() => {
// export async function getStaticProps() でも同じ
  const res = await fetch(`https://spla3.yuu26.com/api/schedule`)
  const schedule = await res.json()
  //console.log("-----------------------------------------------------------------------------")
  //console.log(schedule.result.regular[0])

  return {
    props: { schedule }, // will be passed to the page component as props
  }
}