name: vercel-deploy-hook
on:
  schedule:
    - cron: '0,30,45,15 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call 
        run: |
          curl --request POST \
          --url ${{ secrets.VERCEL_DEPLOYHOOK_URL }}